import { useState } from "react";
import { ToolHeader, CopyButton } from "@/components/ToolPage";
import { Textarea } from "@/components/ui/textarea";

function jsonToGo(json: string, name = "AutoGenerated"): string {
  try {
    const obj = JSON.parse(json);
    return generateStruct(name, obj);
  } catch {
    return "// Invalid JSON";
  }
}

function goType(val: any): string {
  if (val === null) return "interface{}";
  if (typeof val === "string") return "string";
  if (typeof val === "number") return Number.isInteger(val) ? "int" : "float64";
  if (typeof val === "boolean") return "bool";
  if (Array.isArray(val)) return val.length > 0 ? `[]${goType(val[0])}` : "[]interface{}";
  return "interface{}";
}

function toPascal(s: string): string {
  return s.replace(/(?:^|[_\-\s])(\w)/g, (_, c) => c.toUpperCase());
}

function generateStruct(name: string, obj: any): string {
  if (typeof obj !== "object" || obj === null || Array.isArray(obj)) return `type ${name} = ${goType(obj)}`;
  const fields: string[] = [];
  const nested: string[] = [];
  for (const [key, val] of Object.entries(obj)) {
    const fieldName = toPascal(key);
    if (val !== null && typeof val === "object" && !Array.isArray(val)) {
      const structName = fieldName;
      fields.push(`\t${fieldName} ${structName} \`json:"${key}"\``);
      nested.push(generateStruct(structName, val));
    } else if (Array.isArray(val) && val.length > 0 && typeof val[0] === "object" && val[0] !== null) {
      const structName = fieldName + "Item";
      fields.push(`\t${fieldName} []${structName} \`json:"${key}"\``);
      nested.push(generateStruct(structName, val[0]));
    } else {
      fields.push(`\t${fieldName} ${goType(val)} \`json:"${key}"\``);
    }
  }
  return `type ${name} struct {\n${fields.join("\n")}\n}\n${nested.length ? "\n" + nested.join("\n\n") : ""}`;
}

export default function JsonToGoStruct() {
  const [json, setJson] = useState(`{\n  "id": 1,\n  "name": "John Doe",\n  "email": "john@example.com",\n  "active": true,\n  "score": 98.5,\n  "tags": ["admin", "user"],\n  "address": {\n    "street": "123 Main St",\n    "city": "Springfield",\n    "zip": "62704"\n  }\n}`);
  const output = jsonToGo(json);

  return (
    <div className="max-w-3xl mx-auto">
      <ToolHeader title="JSON to Go Struct" description="Convert JSON objects to Go struct definitions" />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <h2 className="text-sm font-semibold text-foreground mb-2">JSON</h2>
          <Textarea value={json} onChange={e => setJson(e.target.value)} className="font-mono text-sm min-h-[300px]" />
        </div>
        <div>
          <div className="flex items-center justify-between mb-2">
            <h2 className="text-sm font-semibold text-foreground">Go Struct</h2>
            <CopyButton text={output} />
          </div>
          <pre className="p-4 bg-muted rounded-lg text-sm font-mono overflow-x-auto whitespace-pre-wrap min-h-[300px] text-foreground">{output}</pre>
        </div>
      </div>
    </div>
  );
}
