import { useState } from "react";
import { ToolHeader, CopyButton } from "@/components/ToolPage";
import { Textarea } from "@/components/ui/textarea";

function jsonToPython(json: string, name = "AutoGenerated"): string {
  try {
    const obj = JSON.parse(json);
    return generateDataclass(name, obj);
  } catch { return "# Invalid JSON"; }
}

function pyType(val: any): string {
  if (val === null) return "Optional[Any]";
  if (typeof val === "string") return "str";
  if (typeof val === "number") return Number.isInteger(val) ? "int" : "float";
  if (typeof val === "boolean") return "bool";
  if (Array.isArray(val)) return val.length > 0 ? `List[${pyType(val[0])}]` : "List[Any]";
  return "Any";
}

function toSnake(s: string): string {
  return s.replace(/([A-Z])/g, "_$1").replace(/^_/, "").toLowerCase().replace(/[- ]/g, "_");
}

function toPascal(s: string): string {
  return s.replace(/(?:^|[_\-\s])(\w)/g, (_, c) => c.toUpperCase());
}

function generateDataclass(name: string, obj: any): string {
  if (typeof obj !== "object" || obj === null || Array.isArray(obj)) return `${name} = ${pyType(obj)}`;
  const fields: string[] = [];
  const nested: string[] = [];
  for (const [key, val] of Object.entries(obj)) {
    const fieldName = toSnake(key);
    if (val !== null && typeof val === "object" && !Array.isArray(val)) {
      const className = toPascal(key);
      fields.push(`    ${fieldName}: ${className}`);
      nested.push(generateDataclass(className, val));
    } else if (Array.isArray(val) && val.length > 0 && typeof val[0] === "object" && val[0] !== null) {
      const className = toPascal(key) + "Item";
      fields.push(`    ${fieldName}: List[${className}]`);
      nested.push(generateDataclass(className, val[0]));
    } else {
      fields.push(`    ${fieldName}: ${pyType(val)}`);
    }
  }
  const imports = "from dataclasses import dataclass\nfrom typing import List, Optional, Any\n\n";
  const nestedStr = nested.length ? nested.join("\n\n") + "\n\n" : "";
  return `${nested.length === 0 ? imports : ""}${nestedStr}@dataclass\nclass ${name}:\n${fields.join("\n")}`;
}

export default function JsonToPython() {
  const [json, setJson] = useState(`{\n  "id": 1,\n  "name": "John Doe",\n  "email": "john@example.com",\n  "active": true,\n  "score": 98.5,\n  "tags": ["admin", "user"],\n  "address": {\n    "street": "123 Main St",\n    "city": "Springfield"\n  }\n}`);
  const output = jsonToPython(json);

  return (
    <div className="max-w-3xl mx-auto">
      <ToolHeader title="JSON to Python" description="Convert JSON to Python dataclass definitions" />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <h2 className="text-sm font-semibold text-foreground mb-2">JSON</h2>
          <Textarea value={json} onChange={e => setJson(e.target.value)} className="font-mono text-sm min-h-[300px]" />
        </div>
        <div>
          <div className="flex items-center justify-between mb-2">
            <h2 className="text-sm font-semibold text-foreground">Python Dataclass</h2>
            <CopyButton text={output} />
          </div>
          <pre className="p-4 bg-muted rounded-lg text-sm font-mono overflow-x-auto whitespace-pre-wrap min-h-[300px] text-foreground">{output}</pre>
        </div>
      </div>
    </div>
  );
}
