import {
  Braces, Binary, Regex, Globe, Clock, Fingerprint, Lock, Palette,
  Shield, FileText, Type, FileSearch, Key, Link, GitCompare, Code, FileCode,
  ArrowLeftRight, Timer, BookOpen, Image, FileUp, Scissors, FileCheck,
  Hash, FileJson, CheckSquare, CaseSensitive, Network, ShieldCheck, List, Table2,
  Paintbrush, Square, AlignHorizontalSpaceBetween, LayoutGrid,
  Blend, Circle, TypeIcon, Ratio, ImageIcon, Smile, Tags, Eye,
  QrCode, LetterText, MapPin, Ruler, FileType, Database, Wind, Wand2,
  FileDiff, Play, GitBranch, Braces as BracesIcon,
  Contrast, SmilePlus, ImagePlus, Quote, Pentagon,
  FileCode as FileCodeIcon, FileX, Settings2, ClockArrowUp, HardDrive,
  Link2, Bot, Map, FileOutput, ImageDown, EyeOff, Hash as HashIcon,
  Camera, FileKey, Monitor,
  TableProperties, Minimize2, Sparkles, Package as PackageIcon, FileEdit,
  ShieldAlert, KeyRound, Webhook, Wifi, LockKeyhole, Box,
  Gauge, CalendarClock, KeySquare, Container, Bug, GitFork, TableIcon, Search, ArrowRightLeft, Radio,
  FileImage, Scaling, Pipette, TerminalSquare, RefreshCw, Wand2 as WandIcon, Crop,
  Waypoints, BookOpenCheck, Zap, PackagePlus, GlassWater, Layers, ArrowRightFromLine, PenTool
} from "lucide-react";

export interface ToolDef {
  id: string;
  title: string;
  description: string;
  icon: any;
  category: string;
  path: string;
}

export const categories = [
  { id: "text-data", label: "Text & Data" },
  { id: "code-testing", label: "Code & Testing" },
  { id: "converters", label: "Converters & Generators" },
  { id: "css-design", label: "CSS & Design" },
  { id: "security", label: "Security" },
  { id: "networking", label: "Networking" },
  { id: "pdf", label: "PDF Tools" },
  { id: "imagery", label: "Image Tools" },
];

export const tools: ToolDef[] = [
  { id: "json-formatter", title: "JSON Formatter", description: "Prettify, minify & validate JSON", icon: Braces, category: "text-data", path: "/tools/json-formatter" },
  { id: "base64", title: "Base64 Encoder", description: "Encode & decode Base64 strings", icon: Binary, category: "text-data", path: "/tools/base64" },
  { id: "markdown-preview", title: "Markdown Preview", description: "Live markdown editor & preview", icon: FileText, category: "text-data", path: "/tools/markdown-preview" },
  { id: "lorem-ipsum", title: "Lorem Ipsum", description: "Generate placeholder text", icon: Type, category: "text-data", path: "/tools/lorem-ipsum" },
  { id: "log-viewer", title: "Log Viewer", description: "Paste & filter log lines", icon: FileSearch, category: "text-data", path: "/tools/log-viewer" },
  { id: "diff-checker", title: "Diff Checker", description: "Compare two texts side by side", icon: GitCompare, category: "text-data", path: "/tools/diff-checker" },
  { id: "json-csv", title: "JSON ↔ CSV", description: "Convert between JSON and CSV", icon: ArrowLeftRight, category: "text-data", path: "/tools/json-csv" },
  { id: "regex-tester", title: "Regex Tester", description: "Test regex with live match highlighting", icon: Regex, category: "code-testing", path: "/tools/regex-tester" },
  { id: "regex-cheatsheet", title: "Regex Cheatsheet", description: "Quick regex syntax reference", icon: BookOpen, category: "code-testing", path: "/tools/regex-cheatsheet" },
  { id: "api-tester", title: "API Tester", description: "Send HTTP requests & view responses", icon: Globe, category: "code-testing", path: "/tools/api-tester" },
  { id: "css-minifier", title: "CSS Minifier", description: "Minify CSS code", icon: Code, category: "code-testing", path: "/tools/css-minifier" },
  { id: "html-entity", title: "HTML Entity Encoder", description: "Encode & decode HTML entities", icon: FileCode, category: "code-testing", path: "/tools/html-entity" },
  { id: "cron-parser", title: "Cron Parser", description: "Parse & understand cron expressions", icon: Timer, category: "code-testing", path: "/tools/cron-parser" },
  { id: "svg-optimizer", title: "SVG Optimizer", description: "Optimize SVG files", icon: Image, category: "code-testing", path: "/tools/svg-optimizer" },
  { id: "timestamp", title: "Timestamp Converter", description: "Convert Unix ↔ human-readable dates", icon: Clock, category: "converters", path: "/tools/timestamp" },
  { id: "uuid-generator", title: "UUID Generator", description: "Generate UUID v4 identifiers", icon: Fingerprint, category: "converters", path: "/tools/uuid-generator" },
  { id: "password-generator", title: "Password Generator", description: "Generate secure passwords", icon: Lock, category: "converters", path: "/tools/password-generator" },
  { id: "color-picker", title: "Color Picker", description: "Pick & convert HEX, RGB, HSL colors", icon: Palette, category: "converters", path: "/tools/color-picker" },
  { id: "url-encoder", title: "URL Encoder/Decoder", description: "Encode & decode URL components", icon: Link, category: "converters", path: "/tools/url-encoder" },
  { id: "jwt-decoder", title: "JWT Decoder", description: "Decode & inspect JSON Web Tokens", icon: Key, category: "security", path: "/tools/jwt-decoder" },
  { id: "hash-generator", title: "Hash Generator", description: "Generate SHA-1, SHA-256, SHA-512 hashes", icon: Shield, category: "security", path: "/tools/hash-generator" },
  { id: "pdf-merger", title: "PDF Merger", description: "Combine multiple PDF files into one", icon: FileUp, category: "pdf", path: "/tools/pdf-merger" },
  { id: "pdf-extractor", title: "PDF Page Extractor", description: "Extract specific pages from a PDF", icon: Scissors, category: "pdf", path: "/tools/pdf-extractor" },
  { id: "pdf-metadata", title: "PDF Metadata Viewer", description: "View PDF properties & metadata", icon: FileCheck, category: "pdf", path: "/tools/pdf-metadata" },
  { id: "number-base", title: "Number Base Converter", description: "Convert between binary, octal, decimal & hex", icon: Hash, category: "converters", path: "/tools/number-base" },
  { id: "yaml-json", title: "YAML ↔ JSON", description: "Convert between YAML and JSON", icon: FileJson, category: "text-data", path: "/tools/yaml-json" },
  { id: "json-schema", title: "JSON Schema Validator", description: "Validate JSON against a schema", icon: CheckSquare, category: "code-testing", path: "/tools/json-schema" },
  { id: "text-case", title: "Text Case Converter", description: "Convert text between different cases", icon: CaseSensitive, category: "text-data", path: "/tools/text-case" },
  { id: "ip-analyzer", title: "IP Address Analyzer", description: "Analyze IPv4 addresses — class, type & binary", icon: Network, category: "code-testing", path: "/tools/ip-analyzer" },
  { id: "unix-permissions", title: "Unix Permissions", description: "Calculate chmod values interactively", icon: ShieldCheck, category: "code-testing", path: "/tools/unix-permissions" },
  { id: "http-status", title: "HTTP Status Codes", description: "Quick reference for HTTP status codes", icon: List, category: "code-testing", path: "/tools/http-status" },
  { id: "markdown-table", title: "Markdown Table Generator", description: "Build markdown tables visually", icon: Table2, category: "text-data", path: "/tools/markdown-table" },
  { id: "color-palette", title: "Color Palette Generator", description: "Generate harmonious color palettes", icon: Paintbrush, category: "css-design", path: "/tools/color-palette" },
  { id: "box-shadow", title: "Box Shadow Generator", description: "Visually design CSS box-shadow values", icon: Square, category: "css-design", path: "/tools/box-shadow" },
  { id: "flexbox", title: "Flexbox Playground", description: "Visualize CSS flexbox properties", icon: AlignHorizontalSpaceBetween, category: "css-design", path: "/tools/flexbox" },
  { id: "css-grid", title: "CSS Grid Generator", description: "Visually build CSS Grid layouts", icon: LayoutGrid, category: "css-design", path: "/tools/css-grid" },
  { id: "gradient", title: "Gradient Generator", description: "Create beautiful CSS gradients visually", icon: Blend, category: "css-design", path: "/tools/gradient" },
  { id: "border-radius", title: "Border Radius Generator", description: "Visually adjust CSS border-radius", icon: Circle, category: "css-design", path: "/tools/border-radius" },
  { id: "text-shadow", title: "Text Shadow Generator", description: "Design CSS text-shadow values", icon: TypeIcon, category: "css-design", path: "/tools/text-shadow" },
  { id: "aspect-ratio", title: "Aspect Ratio Calculator", description: "Calculate and visualize aspect ratios", icon: Ratio, category: "css-design", path: "/tools/aspect-ratio" },
  { id: "base64-image", title: "Base64 Image Encoder", description: "Convert images to Base64 data URIs", icon: ImageIcon, category: "converters", path: "/tools/base64-image" },
  { id: "favicon-generator", title: "Favicon Generator", description: "Generate favicons from emoji", icon: Smile, category: "css-design", path: "/tools/favicon-generator" },
  { id: "meta-tag", title: "Meta Tag Generator", description: "Generate SEO-friendly meta tags", icon: Tags, category: "code-testing", path: "/tools/meta-tag" },
  { id: "og-preview", title: "Open Graph Preview", description: "Preview social media share cards", icon: Eye, category: "code-testing", path: "/tools/og-preview" },
  { id: "qr-code", title: "QR Code Generator", description: "Generate QR codes from text or URLs", icon: QrCode, category: "converters", path: "/tools/qr-code" },
  { id: "char-counter", title: "Character Counter", description: "Count characters, words & reading time", icon: LetterText, category: "text-data", path: "/tools/char-counter" },
  { id: "json-path", title: "JSON Path Finder", description: "Navigate and query JSON with paths", icon: MapPin, category: "text-data", path: "/tools/json-path" },
  { id: "css-unit", title: "CSS Unit Converter", description: "Convert between px, rem, em, vw & more", icon: Ruler, category: "css-design", path: "/tools/css-unit" },
  { id: "encoding", title: "Encoding Converter", description: "Convert between UTF-8, Unicode, Hex & Binary", icon: FileType, category: "converters", path: "/tools/encoding" },
  { id: "sql-formatter", title: "SQL Formatter", description: "Format and beautify SQL queries", icon: Database, category: "code-testing", path: "/tools/sql-formatter" },
  { id: "tailwind", title: "Tailwind Converter", description: "Convert CSS to Tailwind utility classes", icon: Wind, category: "css-design", path: "/tools/tailwind" },
  { id: "regex-generator", title: "Regex Generator", description: "Build regex from presets & patterns", icon: Wand2, category: "code-testing", path: "/tools/regex-generator" },
  { id: "json-diff", title: "JSON Diff Viewer", description: "Compare two JSON objects visually", icon: FileDiff, category: "text-data", path: "/tools/json-diff" },
  { id: "css-animation", title: "CSS Animation Generator", description: "Create CSS keyframe animations", icon: Play, category: "css-design", path: "/tools/css-animation" },
  { id: "git-command", title: "Git Command Builder", description: "Build Git commands interactively", icon: GitBranch, category: "code-testing", path: "/tools/git-command" },
  { id: "ts-type", title: "TS Type Generator", description: "Generate TypeScript types from JSON", icon: BracesIcon, category: "code-testing", path: "/tools/ts-type" },
  { id: "color-contrast", title: "Color Contrast Checker", description: "Check WCAG contrast ratio", icon: Contrast, category: "css-design", path: "/tools/color-contrast" },
  { id: "emoji-picker", title: "Emoji Picker", description: "Browse and copy emojis", icon: SmilePlus, category: "converters", path: "/tools/emoji-picker" },
  { id: "placeholder-image", title: "Placeholder Image", description: "Generate placeholder images", icon: ImagePlus, category: "css-design", path: "/tools/placeholder-image" },
  { id: "string-escaper", title: "String Escape/Unescape", description: "Escape strings for JSON, JS, HTML, URL", icon: Quote, category: "text-data", path: "/tools/string-escaper" },
  { id: "clip-path", title: "CSS Clip Path", description: "Generate CSS clip-path shapes", icon: Pentagon, category: "css-design", path: "/tools/clip-path" },
  { id: "html-preview", title: "HTML Preview", description: "Write HTML with live preview", icon: FileCodeIcon, category: "code-testing", path: "/tools/html-preview" },
  { id: "xml-formatter", title: "XML Formatter", description: "Format and minify XML", icon: FileX, category: "text-data", path: "/tools/xml-formatter" },
  { id: "toml-json", title: "TOML ↔ JSON", description: "Convert between TOML and JSON", icon: Settings2, category: "text-data", path: "/tools/toml-json" },
  { id: "epoch-batch", title: "Epoch Batch Converter", description: "Convert multiple timestamps at once", icon: ClockArrowUp, category: "converters", path: "/tools/epoch-batch" },
  { id: "byte-size", title: "Byte Size Calculator", description: "Convert between byte units", icon: HardDrive, category: "converters", path: "/tools/byte-size" },
  { id: "slug-generator", title: "Slug Generator", description: "Convert text to URL-friendly slugs", icon: Link2, category: "text-data", path: "/tools/slug-generator" },
  { id: "robots-txt", title: "Robots.txt Generator", description: "Generate robots.txt for crawlers", icon: Bot, category: "code-testing", path: "/tools/robots-txt" },
  { id: "sitemap-generator", title: "Sitemap Generator", description: "Generate XML sitemaps for SEO", icon: Map, category: "code-testing", path: "/tools/sitemap-generator" },
  { id: "md-to-html", title: "Markdown to HTML", description: "Convert Markdown to clean HTML", icon: FileOutput, category: "text-data", path: "/tools/md-to-html" },
  { id: "image-compressor", title: "Image Compressor", description: "Compress images in your browser", icon: ImageDown, category: "converters", path: "/tools/image-compressor" },
  { id: "color-blindness", title: "Color Blindness Simulator", description: "Preview colors with color vision deficiency", icon: EyeOff, category: "css-design", path: "/tools/color-blindness" },
  { id: "css-specificity", title: "CSS Specificity Calculator", description: "Calculate CSS selector specificity", icon: HashIcon, category: "css-design", path: "/tools/css-specificity" },
  { id: "code-screenshot", title: "Code Screenshot", description: "Create beautiful code screenshots", icon: Camera, category: "code-testing", path: "/tools/code-screenshot" },
  { id: "htaccess", title: ".htaccess Generator", description: "Generate Apache .htaccess configs", icon: FileKey, category: "code-testing", path: "/tools/htaccess" },
  { id: "responsive-tester", title: "Responsive Tester", description: "Preview websites at different screen sizes", icon: Monitor, category: "code-testing", path: "/tools/responsive-tester" },
  { id: "csv-viewer", title: "CSV Viewer / Editor", description: "View, edit and export CSV data", icon: TableProperties, category: "text-data", path: "/tools/csv-viewer" },
  { id: "html-css-js-minifier", title: "HTML/CSS/JS Minifier", description: "Minify HTML, CSS and JavaScript combined", icon: Minimize2, category: "code-testing", path: "/tools/html-css-js-minifier" },
  { id: "code-beautifier", title: "Code Beautifier", description: "Beautify JSON, CSS, HTML, SQL and XML", icon: Sparkles, category: "code-testing", path: "/tools/code-beautifier" },
  { id: "webpack-config", title: "Webpack Config Generator", description: "Generate webpack.config.js interactively", icon: PackageIcon, category: "code-testing", path: "/tools/webpack-config" },
  { id: "env-editor", title: ".env File Editor", description: "Edit environment variable files visually", icon: FileEdit, category: "code-testing", path: "/tools/env-editor" },
  { id: "cors-checker", title: "CORS Header Checker", description: "Check CORS headers on any URL", icon: ShieldAlert, category: "networking", path: "/tools/cors-checker" },
  { id: "csp-generator", title: "CSP Generator", description: "Generate Content Security Policy headers", icon: LockKeyhole, category: "security", path: "/tools/csp-generator" },
  { id: "totp-generator", title: "TOTP/2FA Generator", description: "Generate time-based one-time passwords", icon: KeyRound, category: "security", path: "/tools/totp-generator" },
  { id: "webhook-tester", title: "Webhook Tester", description: "Send test webhook requests", icon: Webhook, category: "networking", path: "/tools/webhook-tester" },
  { id: "dns-lookup", title: "DNS Lookup", description: "Query DNS records for any domain", icon: Wifi, category: "networking", path: "/tools/dns-lookup" },
  { id: "ssl-decoder", title: "SSL Certificate Decoder", description: "Check and decode SSL certificates", icon: Shield, category: "networking", path: "/tools/ssl-decoder" },
  { id: "npm-size", title: "NPM Package Size", description: "Check bundle size of npm packages", icon: Box, category: "code-testing", path: "/tools/npm-size" },
  { id: "js-benchmark", title: "JS Benchmarker", description: "Compare JavaScript code performance", icon: Gauge, category: "code-testing", path: "/tools/js-benchmark" },
  { id: "cron-builder", title: "Cron Builder", description: "Build cron schedules visually with presets", icon: CalendarClock, category: "code-testing", path: "/tools/cron-builder" },
  { id: "ssh-keygen", title: "SSH Key Generator", description: "Generate RSA/ECDSA key pairs in-browser", icon: KeySquare, category: "security", path: "/tools/ssh-keygen" },
  { id: "docker-compose", title: "Docker Compose Gen", description: "Build docker-compose.yml visually", icon: Container, category: "code-testing", path: "/tools/docker-compose" },
  { id: "regex-debugger", title: "Regex Debugger", description: "Step-by-step regex match visualization", icon: Bug, category: "code-testing", path: "/tools/regex-debugger" },
  { id: "gitignore", title: ".gitignore Generator", description: "Generate .gitignore for any stack", icon: GitFork, category: "code-testing", path: "/tools/gitignore" },
  { id: "ascii-table", title: "ASCII Table Generator", description: "Build text tables for docs & README", icon: TableIcon, category: "text-data", path: "/tools/ascii-table" },
  { id: "http-headers", title: "HTTP Header Inspector", description: "Inspect response headers of any URL", icon: Search, category: "networking", path: "/tools/http-headers" },
  { id: "ts-to-json", title: "TS to JSON", description: "Convert TypeScript interfaces to JSON", icon: ArrowRightLeft, category: "converters", path: "/tools/ts-to-json" },
  { id: "dns-propagation", title: "DNS Propagation", description: "Check DNS propagation across servers", icon: Radio, category: "networking", path: "/tools/dns-propagation" },
  { id: "image-metadata", title: "Image Metadata", description: "Extract EXIF data & file info from images", icon: FileImage, category: "imagery", path: "/tools/image-metadata" },
  { id: "image-resizer", title: "Image Resizer", description: "Resize images to exact dimensions", icon: Scaling, category: "imagery", path: "/tools/image-resizer" },
  { id: "image-colors", title: "Image Color Extractor", description: "Extract dominant colors from images", icon: Pipette, category: "imagery", path: "/tools/image-colors" },
  { id: "image-ascii", title: "Image to ASCII Art", description: "Convert images to ASCII text art", icon: TerminalSquare, category: "imagery", path: "/tools/image-ascii" },
  { id: "image-convert", title: "Image Format Converter", description: "Convert between PNG, JPEG & WebP", icon: RefreshCw, category: "imagery", path: "/tools/image-convert" },
  { id: "image-filters", title: "Image Filters", description: "Apply CSS filters & effects to images", icon: WandIcon, category: "imagery", path: "/tools/image-filters" },
  { id: "image-cropper", title: "Image Cropper", description: "Crop images with aspect ratio lock", icon: Crop, category: "imagery", path: "/tools/image-cropper" },
  { id: "graphql-playground", title: "GraphQL Playground", description: "Send GraphQL queries & view responses", icon: Waypoints, category: "code-testing", path: "/tools/graphql-playground" },
  { id: "openapi-viewer", title: "OpenAPI Viewer", description: "Browse Swagger/OpenAPI specs visually", icon: BookOpenCheck, category: "code-testing", path: "/tools/openapi-viewer" },
  { id: "json-to-zod", title: "JSON to Zod Schema", description: "Generate Zod validation schemas from JSON", icon: Zap, category: "code-testing", path: "/tools/json-to-zod" },
  { id: "package-json", title: "package.json Generator", description: "Build package.json interactively", icon: PackagePlus, category: "code-testing", path: "/tools/package-json" },
  { id: "glassmorphism", title: "Glassmorphism Generator", description: "Create frosted glass UI effects", icon: GlassWater, category: "css-design", path: "/tools/glassmorphism" },
  { id: "neumorphism", title: "Neumorphism Generator", description: "Create soft raised UI elements", icon: Layers, category: "css-design", path: "/tools/neumorphism" },
  { id: "css-transition", title: "CSS Transition Builder", description: "Build multi-property transitions visually", icon: ArrowRightFromLine, category: "css-design", path: "/tools/css-transition" },
  { id: "svg-path-editor", title: "SVG Path Editor", description: "Edit SVG paths with live preview", icon: PenTool, category: "css-design", path: "/tools/svg-path-editor" },
  { id: "nginx-config", title: "Nginx Config Generator", description: "Build production-ready Nginx configs visually", icon: Settings2, category: "code-testing", path: "/tools/nginx-config" },
  { id: "github-actions", title: "GitHub Actions Builder", description: "Build CI/CD workflow YAML with templates", icon: GitBranch, category: "code-testing", path: "/tools/github-actions" },
  { id: "fake-data", title: "Fake Data Generator", description: "Generate realistic fake data for testing", icon: Database, category: "converters", path: "/tools/fake-data" },
];
