import {
  Braces, Binary, Regex, Globe, Clock, Fingerprint, Lock, Palette,
  Shield, FileText, Type, FileSearch, Key, Link, GitCompare, Code, FileCode,
  ArrowLeftRight, Timer, BookOpen, Image, FileUp, Scissors, FileCheck,
  Hash, FileJson, CheckSquare, CaseSensitive, Network, ShieldCheck, List, Table2,
  Paintbrush, Square, AlignHorizontalSpaceBetween, LayoutGrid,
  Blend, Circle, TypeIcon, Ratio, ImageIcon, Smile, Tags, Eye,
  QrCode, LetterText, MapPin, Ruler, FileType, Database, Wind, Wand2,
  FileDiff, Play, GitBranch, Braces as BracesIcon,
  Contrast, SmilePlus, ImagePlus, Quote, Pentagon,
  FileCode as FileCodeIcon, FileX, Settings2, ClockArrowUp, HardDrive,
  Link2, Bot, Map, FileOutput, ImageDown, EyeOff, Hash as HashIcon,
  Camera, FileKey, Monitor,
  TableProperties, Minimize2, Sparkles, Package as PackageIcon, FileEdit,
  ShieldAlert, KeyRound, Webhook, Wifi, LockKeyhole, Box,
  Gauge, CalendarClock, KeySquare, Container, Bug, GitFork, TableIcon, Search, ArrowRightLeft, Radio,
  FileImage, Scaling, Pipette, TerminalSquare, RefreshCw, Wand2 as WandIcon, Crop,
  Waypoints, BookOpenCheck, Zap, PackagePlus, GlassWater, Layers, ArrowRightFromLine, PenTool,
  Plug, TerminalIcon,
  FileCode2, Gem, Apple, TreePine, BarChart3, BookMarked, Calculator,
  CakeSlice, Baby, Heart, DollarSign, Sigma, Compass, Anchor,
  Link as LinkIcon, ScrollText, FileSearch2, Palette as PaletteIcon,
  Columns3, Droplets, Stamp, Grid3x3, RotateCw, FlipHorizontal,
  Scale, BadgePercent, Landmark, History, Trophy
} from "lucide-react";

export interface ToolDef {
  id: string;
  title: string;
  description: string;
  icon: any;
  category: string;
  path: string;
}

export const categories = [
  { id: "text-data", label: "Text & Data" },
  { id: "code-testing", label: "Code & Testing" },
  { id: "converters", label: "Converters & Generators" },
  { id: "css-design", label: "CSS & Design" },
  { id: "security", label: "Security" },
  { id: "networking", label: "Networking" },
  { id: "pdf", label: "PDF Tools" },
  { id: "imagery", label: "Image Tools" },
  { id: "math", label: "Math & Calculators" },
  { id: "seo", label: "SEO" },
];

export const tools: ToolDef[] = [
  // ── Text & Data ──
  { id: "json-formatter", title: "JSON Formatter", description: "Prettify, minify & validate JSON", icon: Braces, category: "text-data", path: "/tools/json-formatter" },
  { id: "base64", title: "Base64 Encoder", description: "Encode & decode Base64 strings", icon: Binary, category: "text-data", path: "/tools/base64" },
  { id: "markdown-preview", title: "Markdown Preview", description: "Live markdown editor & preview", icon: FileText, category: "text-data", path: "/tools/markdown-preview" },
  { id: "lorem-ipsum", title: "Lorem Ipsum", description: "Generate placeholder text", icon: Type, category: "text-data", path: "/tools/lorem-ipsum" },
  { id: "log-viewer", title: "Log Viewer", description: "Paste & filter log lines", icon: FileSearch, category: "text-data", path: "/tools/log-viewer" },
  { id: "diff-checker", title: "Diff Checker", description: "Compare two texts side by side", icon: GitCompare, category: "text-data", path: "/tools/diff-checker" },
  { id: "json-csv", title: "JSON ↔ CSV", description: "Convert between JSON and CSV", icon: ArrowLeftRight, category: "text-data", path: "/tools/json-csv" },
  { id: "yaml-json", title: "YAML ↔ JSON", description: "Convert between YAML and JSON", icon: FileJson, category: "text-data", path: "/tools/yaml-json" },
  { id: "text-case", title: "Text Case Converter", description: "Convert text between different cases", icon: CaseSensitive, category: "text-data", path: "/tools/text-case" },
  { id: "markdown-table", title: "Markdown Table Generator", description: "Build markdown tables visually", icon: Table2, category: "text-data", path: "/tools/markdown-table" },
  { id: "char-counter", title: "Character Counter", description: "Count characters, words & reading time", icon: LetterText, category: "text-data", path: "/tools/char-counter" },
  { id: "json-path", title: "JSON Path Finder", description: "Navigate and query JSON with paths", icon: MapPin, category: "text-data", path: "/tools/json-path" },
  { id: "string-escaper", title: "String Escape/Unescape", description: "Escape strings for JSON, JS, HTML, URL", icon: Quote, category: "text-data", path: "/tools/string-escaper" },
  { id: "xml-formatter", title: "XML Formatter", description: "Format and minify XML", icon: FileX, category: "text-data", path: "/tools/xml-formatter" },
  { id: "toml-json", title: "TOML ↔ JSON", description: "Convert between TOML and JSON", icon: Settings2, category: "text-data", path: "/tools/toml-json" },
  { id: "slug-generator", title: "Slug Generator", description: "Convert text to URL-friendly slugs", icon: Link2, category: "text-data", path: "/tools/slug-generator" },
  { id: "md-to-html", title: "Markdown to HTML", description: "Convert Markdown to clean HTML", icon: FileOutput, category: "text-data", path: "/tools/md-to-html" },
  { id: "json-diff", title: "JSON Diff Viewer", description: "Compare two JSON objects visually", icon: FileDiff, category: "text-data", path: "/tools/json-diff" },
  { id: "csv-viewer", title: "CSV / Excel Viewer", description: "View, sort, filter & edit CSV and Excel files", icon: TableProperties, category: "text-data", path: "/tools/csv-viewer" },
  { id: "ascii-table", title: "ASCII Table Generator", description: "Build text tables for docs & README", icon: TableIcon, category: "text-data", path: "/tools/ascii-table" },
  { id: "pdf-viewer", title: "PDF Viewer", description: "View PDFs with zoom, search & page navigation", icon: FileSearch, category: "text-data", path: "/tools/pdf-viewer" },
  { id: "md-slides", title: "Markdown Slide Presenter", description: "Create presentations from Markdown", icon: Play, category: "text-data", path: "/tools/md-slides" },
  { id: "remove-duplicates", title: "Remove Duplicate Lines", description: "Remove duplicate lines, keep unique entries", icon: FileX, category: "text-data", path: "/tools/remove-duplicates" },
  { id: "sort-lines", title: "Sort Lines", description: "Sort lines alphabetically, by length, numerically", icon: List, category: "text-data", path: "/tools/sort-lines" },
  { id: "word-frequency", title: "Word Frequency Counter", description: "Count word occurrences and frequency", icon: LetterText, category: "text-data", path: "/tools/word-frequency" },
  { id: "text-reverser", title: "Text Reverser", description: "Reverse text by characters, words or lines", icon: ArrowRightLeft, category: "text-data", path: "/tools/text-reverser" },
  { id: "line-numbers", title: "Add/Remove Line Numbers", description: "Add or remove line numbers from text", icon: Hash, category: "text-data", path: "/tools/line-numbers" },
  { id: "text-statistics", title: "Text Statistics", description: "Analyze readability, word count & reading time", icon: BarChart3, category: "text-data", path: "/tools/text-statistics" },
  { id: "markdown-toc", title: "Markdown TOC Generator", description: "Generate Table of Contents from headings", icon: BookMarked, category: "text-data", path: "/tools/markdown-toc" },
  { id: "text-find-replace", title: "Find & Replace", description: "Find and replace text with regex support", icon: Search, category: "text-data", path: "/tools/text-find-replace" },
  { id: "lorem-json", title: "Lorem JSON Generator", description: "Generate random JSON data for testing", icon: Database, category: "text-data", path: "/tools/lorem-json" },
  { id: "text-wrapper", title: "Text Wrapper", description: "Wrap text at a specific character width", icon: ScrollText, category: "text-data", path: "/tools/text-wrapper" },
  { id: "json-flattener", title: "JSON Flattener", description: "Flatten nested JSON or unflatten dot keys", icon: TreePine, category: "text-data", path: "/tools/json-flattener" },

  // ── Code & Testing ──
  { id: "regex-tester", title: "Regex Tester", description: "Test regex with live match highlighting", icon: Regex, category: "code-testing", path: "/tools/regex-tester" },
  { id: "regex-cheatsheet", title: "Regex Cheatsheet", description: "Quick regex syntax reference", icon: BookOpen, category: "code-testing", path: "/tools/regex-cheatsheet" },
  { id: "api-tester", title: "API Tester", description: "Send HTTP requests & view responses", icon: Globe, category: "code-testing", path: "/tools/api-tester" },
  { id: "css-minifier", title: "CSS Minifier", description: "Minify CSS code", icon: Code, category: "code-testing", path: "/tools/css-minifier" },
  { id: "html-entity", title: "HTML Entity Encoder", description: "Encode & decode HTML entities", icon: FileCode, category: "code-testing", path: "/tools/html-entity" },
  { id: "cron-parser", title: "Cron Parser", description: "Parse & understand cron expressions", icon: Timer, category: "code-testing", path: "/tools/cron-parser" },
  { id: "svg-optimizer", title: "SVG Optimizer", description: "Optimize SVG files", icon: Image, category: "code-testing", path: "/tools/svg-optimizer" },
  { id: "json-schema", title: "JSON Schema Validator", description: "Validate JSON against a schema", icon: CheckSquare, category: "code-testing", path: "/tools/json-schema" },
  { id: "ip-analyzer", title: "IP Address Analyzer", description: "Analyze IPv4 addresses — class, type & binary", icon: Network, category: "code-testing", path: "/tools/ip-analyzer" },
  { id: "unix-permissions", title: "Unix Permissions", description: "Calculate chmod values interactively", icon: ShieldCheck, category: "code-testing", path: "/tools/unix-permissions" },
  { id: "http-status", title: "HTTP Status Codes", description: "Quick reference for HTTP status codes", icon: List, category: "code-testing", path: "/tools/http-status" },
  { id: "sql-formatter", title: "SQL Formatter", description: "Format and beautify SQL queries", icon: Database, category: "code-testing", path: "/tools/sql-formatter" },
  { id: "regex-generator", title: "Regex Generator", description: "Build regex from presets & patterns", icon: Wand2, category: "code-testing", path: "/tools/regex-generator" },
  { id: "git-command", title: "Git Command Builder", description: "Build Git commands interactively", icon: GitBranch, category: "code-testing", path: "/tools/git-command" },
  { id: "ts-type", title: "TS Type Generator", description: "Generate TypeScript types from JSON", icon: BracesIcon, category: "code-testing", path: "/tools/ts-type" },
  { id: "html-preview", title: "HTML Preview", description: "Write HTML with live preview", icon: FileCodeIcon, category: "code-testing", path: "/tools/html-preview" },
  { id: "meta-tag", title: "Meta Tag Generator", description: "Generate SEO-friendly meta tags", icon: Tags, category: "code-testing", path: "/tools/meta-tag" },
  { id: "og-preview", title: "Open Graph Preview", description: "Preview social media share cards", icon: Eye, category: "code-testing", path: "/tools/og-preview" },
  { id: "html-css-js-minifier", title: "HTML/CSS/JS Minifier", description: "Minify HTML, CSS and JavaScript combined", icon: Minimize2, category: "code-testing", path: "/tools/html-css-js-minifier" },
  { id: "code-beautifier", title: "Code Beautifier", description: "Beautify JSON, CSS, HTML, SQL and XML", icon: Sparkles, category: "code-testing", path: "/tools/code-beautifier" },
  { id: "webpack-config", title: "Webpack Config Generator", description: "Generate webpack.config.js interactively", icon: PackageIcon, category: "code-testing", path: "/tools/webpack-config" },
  { id: "env-editor", title: ".env File Editor", description: "Edit environment variable files visually", icon: FileEdit, category: "code-testing", path: "/tools/env-editor" },
  { id: "npm-size", title: "NPM Package Size", description: "Check bundle size of npm packages", icon: Box, category: "code-testing", path: "/tools/npm-size" },
  { id: "js-benchmark", title: "JS Benchmarker", description: "Compare JavaScript code performance", icon: Gauge, category: "code-testing", path: "/tools/js-benchmark" },
  { id: "cron-builder", title: "Cron Builder", description: "Build cron schedules visually with presets", icon: CalendarClock, category: "code-testing", path: "/tools/cron-builder" },
  { id: "docker-compose", title: "Docker Compose Gen", description: "Build docker-compose.yml visually", icon: Container, category: "code-testing", path: "/tools/docker-compose" },
  { id: "regex-debugger", title: "Regex Debugger", description: "Step-by-step regex match visualization", icon: Bug, category: "code-testing", path: "/tools/regex-debugger" },
  { id: "gitignore", title: ".gitignore Generator", description: "Generate .gitignore for any stack", icon: GitFork, category: "code-testing", path: "/tools/gitignore" },
  { id: "code-screenshot", title: "Code Screenshot", description: "Create beautiful code screenshots", icon: Camera, category: "code-testing", path: "/tools/code-screenshot" },
  { id: "htaccess", title: ".htaccess Generator", description: "Generate Apache .htaccess configs", icon: FileKey, category: "code-testing", path: "/tools/htaccess" },
  { id: "responsive-tester", title: "Responsive Tester", description: "Preview websites at different screen sizes", icon: Monitor, category: "code-testing", path: "/tools/responsive-tester" },
  { id: "graphql-playground", title: "GraphQL Playground", description: "Send GraphQL queries & view responses", icon: Waypoints, category: "code-testing", path: "/tools/graphql-playground" },
  { id: "openapi-viewer", title: "OpenAPI Viewer", description: "Browse Swagger/OpenAPI specs visually", icon: BookOpenCheck, category: "code-testing", path: "/tools/openapi-viewer" },
  { id: "json-to-zod", title: "JSON to Zod Schema", description: "Generate Zod validation schemas from JSON", icon: Zap, category: "code-testing", path: "/tools/json-to-zod" },
  { id: "package-json", title: "package.json Generator", description: "Build package.json interactively", icon: PackagePlus, category: "code-testing", path: "/tools/package-json" },
  { id: "nginx-config", title: "Nginx Config Generator", description: "Build production-ready Nginx configs visually", icon: Settings2, category: "code-testing", path: "/tools/nginx-config" },
  { id: "github-actions", title: "GitHub Actions Builder", description: "Build CI/CD workflow YAML with templates", icon: GitBranch, category: "code-testing", path: "/tools/github-actions" },
  { id: "sql-playground", title: "SQL Playground", description: "Run SQL queries in-browser with SQLite", icon: TerminalIcon, category: "code-testing", path: "/tools/sql-playground" },
  { id: "mongo-query", title: "MongoDB Query Builder", description: "Build MongoDB find & aggregate queries visually", icon: Database, category: "code-testing", path: "/tools/mongo-query" },
  { id: "websocket-tester", title: "WebSocket Tester", description: "Connect to WebSocket servers and test messages", icon: Plug, category: "code-testing", path: "/tools/websocket-tester" },
  { id: "readme-generator", title: "README Generator", description: "Generate README.md for your projects", icon: FileText, category: "code-testing", path: "/tools/readme-generator" },
  { id: "eslint-config", title: "ESLint Config Generator", description: "Generate .eslintrc.json interactively", icon: Settings2, category: "code-testing", path: "/tools/eslint-config" },
  { id: "tsconfig-gen", title: "tsconfig.json Generator", description: "Generate TypeScript config interactively", icon: FileCode2, category: "code-testing", path: "/tools/tsconfig-gen" },
  { id: "editorconfig-gen", title: "EditorConfig Generator", description: "Generate .editorconfig for consistent coding styles", icon: FileEdit, category: "code-testing", path: "/tools/editorconfig-gen" },
  { id: "prettier-config", title: "Prettier Config Generator", description: "Generate .prettierrc configuration", icon: Sparkles, category: "code-testing", path: "/tools/prettier-config" },
  { id: "license-gen", title: "License Generator", description: "Generate open source license files", icon: Scale, category: "code-testing", path: "/tools/license-gen" },
  { id: "changelog-gen", title: "Changelog Generator", description: "Generate CHANGELOG.md entries", icon: History, category: "code-testing", path: "/tools/changelog-gen" },

  // ── Converters & Generators ──
  { id: "timestamp", title: "Timestamp Converter", description: "Convert Unix ↔ human-readable dates", icon: Clock, category: "converters", path: "/tools/timestamp" },
  { id: "uuid-generator", title: "UUID Generator", description: "Generate UUID v4 identifiers", icon: Fingerprint, category: "converters", path: "/tools/uuid-generator" },
  { id: "password-generator", title: "Password Generator", description: "Generate secure passwords", icon: Lock, category: "converters", path: "/tools/password-generator" },
  { id: "color-picker", title: "Color Picker", description: "Pick & convert HEX, RGB, HSL colors", icon: Palette, category: "converters", path: "/tools/color-picker" },
  { id: "url-encoder", title: "URL Encoder/Decoder", description: "Encode & decode URL components", icon: Link, category: "converters", path: "/tools/url-encoder" },
  { id: "number-base", title: "Number Base Converter", description: "Convert between binary, octal, decimal & hex", icon: Hash, category: "converters", path: "/tools/number-base" },
  { id: "base64-image", title: "Base64 Image Encoder", description: "Convert images to Base64 data URIs", icon: ImageIcon, category: "converters", path: "/tools/base64-image" },
  { id: "qr-code", title: "QR Code Generator", description: "Generate QR codes from text or URLs", icon: QrCode, category: "converters", path: "/tools/qr-code" },
  { id: "encoding", title: "Encoding Converter", description: "Convert between UTF-8, Unicode, Hex & Binary", icon: FileType, category: "converters", path: "/tools/encoding" },
  { id: "epoch-batch", title: "Epoch Batch Converter", description: "Convert multiple timestamps at once", icon: ClockArrowUp, category: "converters", path: "/tools/epoch-batch" },
  { id: "byte-size", title: "Byte Size Calculator", description: "Convert between byte units", icon: HardDrive, category: "converters", path: "/tools/byte-size" },
  { id: "image-compressor", title: "Image Compressor", description: "Compress images in your browser", icon: ImageDown, category: "converters", path: "/tools/image-compressor" },
  { id: "emoji-picker", title: "Emoji Picker", description: "Browse and copy emojis", icon: SmilePlus, category: "converters", path: "/tools/emoji-picker" },
  { id: "ts-to-json", title: "TS to JSON", description: "Convert TypeScript interfaces to JSON", icon: ArrowRightLeft, category: "converters", path: "/tools/ts-to-json" },
  { id: "fake-data", title: "Fake Data Generator", description: "Generate realistic fake data for testing", icon: Database, category: "converters", path: "/tools/fake-data" },
  { id: "curl-to-code", title: "cURL to Code", description: "Convert cURL commands to JS, Python, PHP, Go, Ruby", icon: ArrowRightLeft, category: "converters", path: "/tools/curl-to-code" },
  { id: "html-to-jsx", title: "HTML to JSX", description: "Convert HTML markup to valid JSX syntax", icon: FileCode, category: "converters", path: "/tools/html-to-jsx" },
  { id: "json-to-go", title: "JSON to Go Struct", description: "Convert JSON objects to Go struct definitions", icon: Braces, category: "converters", path: "/tools/json-to-go" },
  { id: "html-to-markdown", title: "HTML to Markdown", description: "Convert HTML markup to clean Markdown", icon: FileOutput, category: "converters", path: "/tools/html-to-markdown" },
  { id: "json-to-python", title: "JSON to Python", description: "Convert JSON to Python dataclass definitions", icon: Braces, category: "converters", path: "/tools/json-to-python" },
  { id: "json-to-xml", title: "JSON to XML", description: "Convert JSON data to XML format", icon: FileCode, category: "converters", path: "/tools/json-to-xml" },
  { id: "json-to-rust", title: "JSON to Rust Struct", description: "Convert JSON to Rust struct with serde", icon: Gem, category: "converters", path: "/tools/json-to-rust" },
  { id: "json-to-kotlin", title: "JSON to Kotlin", description: "Convert JSON to Kotlin data class", icon: FileCode2, category: "converters", path: "/tools/json-to-kotlin" },
  { id: "json-to-swift", title: "JSON to Swift", description: "Convert JSON to Swift Codable struct", icon: Apple, category: "converters", path: "/tools/json-to-swift" },

  // ── CSS & Design ──
  { id: "color-palette", title: "Color Palette Generator", description: "Generate harmonious color palettes", icon: Paintbrush, category: "css-design", path: "/tools/color-palette" },
  { id: "box-shadow", title: "Box Shadow Generator", description: "Visually design CSS box-shadow values", icon: Square, category: "css-design", path: "/tools/box-shadow" },
  { id: "flexbox", title: "Flexbox Playground", description: "Visualize CSS flexbox properties", icon: AlignHorizontalSpaceBetween, category: "css-design", path: "/tools/flexbox" },
  { id: "css-grid", title: "CSS Grid Generator", description: "Visually build CSS Grid layouts", icon: LayoutGrid, category: "css-design", path: "/tools/css-grid" },
  { id: "gradient", title: "Gradient Generator", description: "Create beautiful CSS gradients visually", icon: Blend, category: "css-design", path: "/tools/gradient" },
  { id: "border-radius", title: "Border Radius Generator", description: "Visually adjust CSS border-radius", icon: Circle, category: "css-design", path: "/tools/border-radius" },
  { id: "text-shadow", title: "Text Shadow Generator", description: "Design CSS text-shadow values", icon: TypeIcon, category: "css-design", path: "/tools/text-shadow" },
  { id: "aspect-ratio", title: "Aspect Ratio Calculator", description: "Calculate and visualize aspect ratios", icon: Ratio, category: "css-design", path: "/tools/aspect-ratio" },
  { id: "favicon-generator", title: "Favicon Generator", description: "Generate favicons from emoji", icon: Smile, category: "css-design", path: "/tools/favicon-generator" },
  { id: "css-unit", title: "CSS Unit Converter", description: "Convert between px, rem, em, vw & more", icon: Ruler, category: "css-design", path: "/tools/css-unit" },
  { id: "tailwind", title: "Tailwind Converter", description: "Convert CSS to Tailwind utility classes", icon: Wind, category: "css-design", path: "/tools/tailwind" },
  { id: "css-animation", title: "CSS Animation Generator", description: "Create CSS keyframe animations", icon: Play, category: "css-design", path: "/tools/css-animation" },
  { id: "color-contrast", title: "Color Contrast Checker", description: "Check WCAG contrast ratio", icon: Contrast, category: "css-design", path: "/tools/color-contrast" },
  { id: "placeholder-image", title: "Placeholder Image", description: "Generate placeholder images", icon: ImagePlus, category: "css-design", path: "/tools/placeholder-image" },
  { id: "clip-path", title: "CSS Clip Path", description: "Generate CSS clip-path shapes", icon: Pentagon, category: "css-design", path: "/tools/clip-path" },
  { id: "color-blindness", title: "Color Blindness Simulator", description: "Preview colors with color vision deficiency", icon: EyeOff, category: "css-design", path: "/tools/color-blindness" },
  { id: "css-specificity", title: "CSS Specificity Calculator", description: "Calculate CSS selector specificity", icon: HashIcon, category: "css-design", path: "/tools/css-specificity" },
  { id: "glassmorphism", title: "Glassmorphism Generator", description: "Create frosted glass UI effects", icon: GlassWater, category: "css-design", path: "/tools/glassmorphism" },
  { id: "neumorphism", title: "Neumorphism Generator", description: "Create soft raised UI elements", icon: Layers, category: "css-design", path: "/tools/neumorphism" },
  { id: "css-transition", title: "CSS Transition Builder", description: "Build multi-property transitions visually", icon: ArrowRightFromLine, category: "css-design", path: "/tools/css-transition" },
  { id: "svg-path-editor", title: "SVG Path Editor", description: "Edit SVG paths with live preview", icon: PenTool, category: "css-design", path: "/tools/svg-path-editor" },
  { id: "color-mixer", title: "Color Mixer", description: "Mix two colors and generate color steps", icon: Droplets, category: "css-design", path: "/tools/color-mixer" },
  { id: "font-pair", title: "Font Pair Generator", description: "Discover beautiful font pairings", icon: TypeIcon, category: "css-design", path: "/tools/font-pair" },
  { id: "css-filter-gen", title: "CSS Filter Generator", description: "Generate CSS filter effects visually", icon: WandIcon, category: "css-design", path: "/tools/css-filter-gen" },
  { id: "css-columns", title: "CSS Columns Generator", description: "Generate multi-column layouts visually", icon: Columns3, category: "css-design", path: "/tools/css-columns" },

  // ── Security ──
  { id: "jwt-decoder", title: "JWT Decoder", description: "Decode & inspect JSON Web Tokens", icon: Key, category: "security", path: "/tools/jwt-decoder" },
  { id: "hash-generator", title: "Hash Generator", description: "Generate SHA-1, SHA-256, SHA-512 hashes", icon: Shield, category: "security", path: "/tools/hash-generator" },
  { id: "csp-generator", title: "CSP Generator", description: "Generate Content Security Policy headers", icon: LockKeyhole, category: "security", path: "/tools/csp-generator" },
  { id: "totp-generator", title: "TOTP/2FA Generator", description: "Generate time-based one-time passwords", icon: KeyRound, category: "security", path: "/tools/totp-generator" },
  { id: "ssh-keygen", title: "SSH Key Generator", description: "Generate RSA/ECDSA key pairs in-browser", icon: KeySquare, category: "security", path: "/tools/ssh-keygen" },
  { id: "password-strength", title: "Password Strength", description: "Analyze password strength, entropy & crack time", icon: ShieldCheck, category: "security", path: "/tools/password-strength" },
  { id: "aes-encryption", title: "AES Encryption", description: "Encrypt/decrypt text with AES-256-GCM", icon: LockKeyhole, category: "security", path: "/tools/aes-encryption" },
  { id: "cipher-tools", title: "Cipher & Encoding", description: "ROT13, Caesar cipher and Morse code converter", icon: Lock, category: "security", path: "/tools/cipher-tools" },
  { id: "hmac-generator", title: "HMAC Generator", description: "Generate HMAC signatures with SHA-256/384/512", icon: Shield, category: "security", path: "/tools/hmac-generator" },
  { id: "sri-hash", title: "SRI Hash Generator", description: "Generate Subresource Integrity hashes", icon: ShieldCheck, category: "security", path: "/tools/sri-hash" },
  { id: "base32", title: "Base32 Encoder/Decoder", description: "Encode and decode Base32 strings", icon: Binary, category: "security", path: "/tools/base32" },

  // ── Networking ──
  { id: "cors-checker", title: "CORS Header Checker", description: "Check CORS headers on any URL", icon: ShieldAlert, category: "networking", path: "/tools/cors-checker" },
  { id: "webhook-tester", title: "Webhook Tester", description: "Send test webhook requests", icon: Webhook, category: "networking", path: "/tools/webhook-tester" },
  { id: "dns-lookup", title: "DNS Checker", description: "Query DNS records for any domain", icon: Wifi, category: "networking", path: "/tools/dns-lookup" },
  { id: "domain-checker", title: "Domain Checker", description: "Check domain registration and WHOIS details", icon: Globe, category: "networking", path: "/tools/domain-checker" },
  { id: "ssl-decoder", title: "SSL Certificate Decoder", description: "Check and decode SSL certificates", icon: Shield, category: "networking", path: "/tools/ssl-decoder" },
  { id: "http-headers", title: "HTTP Header Inspector", description: "Inspect response headers of any URL", icon: Search, category: "networking", path: "/tools/http-headers" },
  { id: "dns-propagation", title: "DNS Propagation", description: "Check DNS propagation across servers", icon: Radio, category: "networking", path: "/tools/dns-propagation" },
  { id: "subnet-calc", title: "Subnet Calculator", description: "Calculate subnet details from IP/CIDR notation", icon: Network, category: "networking", path: "/tools/subnet-calc" },
  { id: "user-agent-parser", title: "User Agent Parser", description: "Parse and analyze browser user agent strings", icon: Compass, category: "networking", path: "/tools/user-agent-parser" },
  { id: "port-reference", title: "Common Ports Reference", description: "Quick reference for well-known network ports", icon: Anchor, category: "networking", path: "/tools/port-reference" },
  { id: "url-parser", title: "URL Parser", description: "Parse and analyze URL components", icon: LinkIcon, category: "networking", path: "/tools/url-parser" },
  { id: "http-method-ref", title: "HTTP Methods Reference", description: "Quick reference for HTTP request methods", icon: ScrollText, category: "networking", path: "/tools/http-method-ref" },

  // ── PDF Tools ──
  { id: "pdf-merger", title: "PDF Merger", description: "Combine multiple PDF files into one", icon: FileUp, category: "pdf", path: "/tools/pdf-merger" },
  { id: "pdf-extractor", title: "PDF Page Extractor", description: "Extract specific pages from a PDF", icon: Scissors, category: "pdf", path: "/tools/pdf-extractor" },
  { id: "pdf-metadata", title: "PDF Metadata Viewer", description: "View PDF properties & metadata", icon: FileCheck, category: "pdf", path: "/tools/pdf-metadata" },

  // ── Image Tools ──
  { id: "image-metadata", title: "Image Metadata", description: "Extract EXIF data & file info from images", icon: FileImage, category: "imagery", path: "/tools/image-metadata" },
  { id: "image-resizer", title: "Image Resizer", description: "Resize images to exact dimensions", icon: Scaling, category: "imagery", path: "/tools/image-resizer" },
  { id: "image-colors", title: "Image Color Extractor", description: "Extract dominant colors from images", icon: Pipette, category: "imagery", path: "/tools/image-colors" },
  { id: "image-ascii", title: "Image to ASCII Art", description: "Convert images to ASCII text art", icon: TerminalSquare, category: "imagery", path: "/tools/image-ascii" },
  { id: "image-convert", title: "Image Format Converter", description: "Convert between PNG, JPEG & WebP", icon: RefreshCw, category: "imagery", path: "/tools/image-convert" },
  { id: "image-filters", title: "Image Filters", description: "Apply CSS filters & effects to images", icon: WandIcon, category: "imagery", path: "/tools/image-filters" },
  { id: "image-cropper", title: "Image Cropper", description: "Crop images with aspect ratio lock", icon: Crop, category: "imagery", path: "/tools/image-cropper" },
  { id: "image-watermark", title: "Image Watermark", description: "Add text watermark to images", icon: Stamp, category: "imagery", path: "/tools/image-watermark" },
  { id: "image-pixelate", title: "Image Pixelate", description: "Pixelate images with adjustable block size", icon: Grid3x3, category: "imagery", path: "/tools/image-pixelate" },
  { id: "image-flip-rotate", title: "Image Flip & Rotate", description: "Flip and rotate images with one click", icon: FlipHorizontal, category: "imagery", path: "/tools/image-flip-rotate" },

  // ── Math & Calculators ──
  { id: "unit-converter", title: "Unit Converter", description: "Convert length, weight, temperature, speed & area", icon: Ruler, category: "math", path: "/tools/unit-converter" },
  { id: "percentage-calc", title: "Percentage Calculator", description: "Calculate percentages, change, increase/decrease", icon: BadgePercent, category: "math", path: "/tools/percentage-calc" },
  { id: "date-calculator", title: "Date Calculator", description: "Add/subtract days, calculate date differences", icon: CalendarClock, category: "math", path: "/tools/date-calculator" },
  { id: "timezone-converter", title: "Timezone Converter", description: "Convert time between different timezones", icon: Clock, category: "math", path: "/tools/timezone-converter" },
  { id: "age-calculator", title: "Age Calculator", description: "Calculate exact age from date of birth", icon: Baby, category: "math", path: "/tools/age-calculator" },
  { id: "bmi-calculator", title: "BMI Calculator", description: "Calculate Body Mass Index from weight & height", icon: Heart, category: "math", path: "/tools/bmi-calculator" },
  { id: "loan-calculator", title: "Loan/EMI Calculator", description: "Calculate monthly EMI, total payment & interest", icon: Landmark, category: "math", path: "/tools/loan-calculator" },
  { id: "tip-calculator", title: "Tip Calculator", description: "Calculate tip amount and split between people", icon: DollarSign, category: "math", path: "/tools/tip-calculator" },
  { id: "discount-calc", title: "Discount Calculator", description: "Calculate discounted price and savings", icon: BadgePercent, category: "math", path: "/tools/discount-calc" },
  { id: "scientific-calc", title: "Scientific Calculator", description: "Calculator with sin, cos, tan, log, sqrt", icon: Sigma, category: "math", path: "/tools/scientific-calc" },

  // ── SEO ──
  { id: "robots-txt", title: "Robots.txt Generator", description: "Generate robots.txt for crawlers", icon: Bot, category: "seo", path: "/tools/robots-txt" },
  { id: "sitemap-generator", title: "Sitemap Generator", description: "Generate XML sitemaps for SEO", icon: Map, category: "seo", path: "/tools/sitemap-generator" },
  { id: "structured-data", title: "JSON-LD Generator", description: "Generate structured data markup for SEO", icon: FileSearch2, category: "seo", path: "/tools/structured-data" },
  { id: "cms-checker", title: "CMS Checker", description: "Detect what CMS or framework a website uses", icon: Search, category: "seo", path: "/tools/cms-checker" },
];
